# @package _global_

training:
  soft_logits: false
  reg_with_base_weight: 0.0
  reg_weight: 0.0
  loss_last: false

drafting_features: 
  tokens: sampled 

drafting_params: 
  speculation_len: 7

tag: 'kl_token'